''''
Based on the book
'Hands on ML Trading Algorithms'
chapter 4: Develop a conceptual understanding of key factor categories, their rationales and popular metrics.
Numpy and pandas are key tools for custom factor computation.
'''

import warnings
from datetime import datetime
import os
from pathlib import Path
import quandl
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import pandas_datareader.data as web
from sklearn.feature_selection import mutual_info_classif
from pyfinance.ols import PandasRollingOLS

warnings.filterwarnings('ignore')
plt.style.use('fivethirtyeight')
idx = pd.IndexSlice

'''
GetData 
The store assets.h5 file is generated by create_dataset.py in the data directory
'''
DATA_STORE = "../../data/assets.h5"